### PR TITLE
Fix #10 Support different hosts for API and Website

### LINKED ISSUE #10: Link generation is broken since JIRA migration to RMD
Link generation is broken – need patch on [hubot-jira-issue-fetcher/messageFormatter.js at master · AirVantage/hubot-jira-issue-fetcher (github.com)](https://github.com/AirVantage/hubot-jira-issue-fetcher/blob/master/lib/messageFormatter.js#L39)

### PR DESCRIPTION
**Pull request by sebz**
Thought I would be able to get the correct URL directly from the JSON result of the details but they don't provide it...

```json
{
	  "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
	  "id": "48539",
	  "self": "https://issues.sierrawireless.com/rest/api/2/issue/48539",
	  "key": "OPE-233",
	  "fields": {
	  "customfield_12010": null,
	  "customfield_11562": null,
	  "customfield_15123": null,
	  "fixVersions": [],
	  "customfield_10110": "9223372036854775807",
	  "customfield_12012": null,
	  "customfield_11321": null,
	  "customfield_12411": null,
	[...]
}
```
And instead of trying to compute it from some URLs we can find in the JSON, I decided to add another config parameter to have both the API host and the Website host.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -4,19 +4,25 @@ const messageFormatter = require('./lib/messageFormatter');
...
   JIRA_KEY_MATCHER = /[A-Z0-9]*-\d+/i;
 let bot;
 
+const DEBUG = (message) => {
+  bot.logger.debug('JIRA-ISSUE-FETCHER: ' + message);
+}
+
 module.exports = (robot) => {
   bot = robot;
+  DEBUG('Started!');
```
Comment (jlescot) [inline index.js:25]: Do we want to keep this DEBUG log on startup?

**Review by jlescot — APPROVED** [review]

File: index.js (hunk 1 above)
Comment (sebz) [reply index.js:25]: Yes, I thought it could be used to at least know if this script starts :)
